import { Header, ProfileCard, Sections } from "@/components";
import { Navbar } from "@/components/sections/navbar";
import { DataProvider } from "@/context/data-provider";
import { bodyStyle, containerStyle, mainStyle, sectionStyle } from "@/styles";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={bodyStyle}>
        <DataProvider>
          <main className={mainStyle}>
            <Header />
            <div className={containerStyle}>
              <ProfileCard />
              <div className={sectionStyle}>
                <Navbar />
                {children}
              </div>
            </div>
          </main>
        </DataProvider>
      </body>
    </html>
  );
}
